package cpu.microarchitecture;

public enum MicroarchitectureEventType {
    FETCH_BYTE, QUEUE_PUSH, QUEUE_POP, EU_START, EU_COMPLETE,
    MEM_READ, MEM_WRITE, BUS_BUSY, EU_STALL, BIU_STALL, QUEUE_EMPTY,
    QUEUE_FULL, CONTROL_TRANSFER, QUEUE_FLUSH, INSTRUCTION_RETIRE
}
